### ISSUE TITLE
Recommended procedure for local harvesting

### ISSUE THREAD

**Issue by GodTanu** [nemtech/symbol-bootstrap#96]
In v0.3.1, `nodeUseRemoteAccount:` is : true.
How do I do local harvesting in this case?

When I run the Link command, I get a message that the remote account needs XYM.
It is strange to deposit XYM into a remote account.

Please let me know the recommended procedure.
If I want to do local harvesting, do I have to set `nodeUseRemoteAccount:false`?

**Comment by fboucquez** [comment]
Hi @GodTanu , bootstrap supports 2 modes of harvesting:

### 1 - Local Harvest
Node owner using Main account as harvesting private key (Unsecure / Not Recommended):

Requirements:

- Main, VRF, Node accounts
- Main account with tokens (example 3m)
- ca.cert.pem using Main Account
- node.crt.pem using Node Account
- Main -> config-harvesting.properties harvesterSigningPrivateKey
- VRF -> config-harvesting.properties harvesterVrfPrivateKey
- VrfKeyLinkTransaction from Main to VRF 

Disabled by default (because it's insecure), can be turned on in bootstrap with a `nodeUseRemoteAccount: false` preset flag.

### 2 - Remote Harvest
Node owner using Remote account as harvesting private key (Recommended, main private key is NOT stored in config files): 

Requirements:

- Main, VRF, Node, Remote accounts
- Main account with tokens (example 3m)
- ca.cert.pem using Main Account
- node.crt.pem using Node Account
- Remote -> config-harvesting.properties harvesterSigningPrivateKey
- VRF -> config-harvesting.properties harvesterVrfPrivateKey
- VrfKeyLinkTransaction from Main to VRF public key
- AccountKeyLinkTransaction from Main to Remote public key
- NodeKeyLinkTransaction from Main to Node public key

The default setup in bootstrap (nodeUseRemoteAccount: true by default)

### Steps

There is nothing special to do. By default, bootstrap uses Remote Harvesting which is the recommended harvesting mode. You can disable it but your main account private key must be installed in your server inside config-harvesting.properties. If your server is compromised, the private key of your main account with all the tokens may be compromised.

The steps to run a harvesting node is the same as https://docs.symbolplatform.com/guides/network/running-a-test-net-node.html. Your main account would need enough tokens and you need the `link` account to finish your node accounts registrations.

The addresses.yml and prest.yml don't need to be in your server when the node is running. They should stay private.

Having said that, we have added --password 'somePassword' to the commands in bootstrap. This param encrypts and decrypts the private keys on address.yml and preset.yml for extra security.

**Comment by GodTanu** [comment]
Simply put, is remote harvesting the same as doing delegated harvesting?

**Comment by fboucquez** [comment]
No no, Delegate Harvesting would be the third option that doesn't apply to bootstrap directly. 

 ### 3 - Delegate Harvest

Regular user delegating harvesting to a known node. The user is not a node owner (necessarily).

Requirements

- Main (User) VRF, Remote accounts
- Main account with tokens (example 10k)
- VrfKeyLinkTransaction from Main to VRF public key
- AccountKeyLinkTransaction from Main to Remote public key
- NodeKeyLinkTransaction from Main to Node public key
- PersistentDelegationRequestTransaction from main to node account with the special encrypted message (including the user's vrf private key and remote private key)

Not required/related to bootstrap. Regular users can enable it via the Wallet.

NOTE: PersistentDelegationRequestTransaction is required only for delegate harvesting and not for node admins or supernodes.

**Comment by GodTanu** [comment]
I'm sorry for repeating myself.
Let me clear up my perception.

1. Local Harvest
2. Remote Harvest

There are two types of


Local Harvest

Set nodeUseRemoteAccount: false in config
Set main account to config-harvesting.propertiesharvesterSigningPrivateKey
symbol-bootstrap link

2. Remote Harvesting
Set nodeUseRemoteAccount: false(Default) in config
symbol-bootstrap link

Are there any missing steps in the above steps?

**Comment by segfaultxavi** [comment]
The harvesting Conceptual docs have been updated, maybe that can help with the discussion:
https://docs.symbolplatform.com/concepts/harvesting.html#harvesting-types
(The harvesting Setup guides will come next)

**Comment by GodTanu** [comment]
Thanks. My questions were completely cleared up.
